spring:
  application:
  name: WebBackEnd
  datasource:
    url: jdbc:mysql://localhost:3306/webbackend
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  security:
    user:
      name: admin
      password: admin
  servlet:
    multipart:
      enabled: true
springdoc:
  swagger-ui:
    path: swagger-ui.html
    operations-sorter: method